services:
  api:
    build:
      context: evalrag
      dockerfile: Dockerfile

    volumes:
      - . :/app

    ports:
      - "8000:8000"

    container_name: rag_api

    env_file:
      - .env
  # web:
  # build:
  # context: contextPath
  # dockerfile: Dockerfile
